### ISSUE TITLE
Error loading: (IndexError: tuple index out of range)

### ISSUE THREAD

**Issue by iculookn** [azerty9971/xtend_tuya#121]
Hello, I am getting an error on startup

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 11:26:00 AM (1 occurrences)
Last logged: 11:26:00 AM

Error setting up entry iculookn@gmail.com for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 63, in async_setup_entry
    await cleanup_device_registry(hass, multi_manager, entry)
  File "/config/custom_components/xtend_tuya/__init__.py", line 104, in cleanup_device_registry
    if not is_device_in_domain_device_maps(hass, [DOMAIN_ORIG, DOMAIN],item):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 128, in is_device_in_domain_device_maps
    device_id = device_entry_identifiers[1]
                ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

```

I have tried 2.0.7 and the latest beta.
I have tried adding a Open API account, no difference.
On launch it says configured successfully, but then shows as "failed to setup"
HA Ver: 2024.10.2

Anything I can check and fix?

Thanks,

**Comment by azerty9971** [comment]
Hello,
This should be fixed in v3.0.0 (already published).

Don't hesitate to let me know if you still have this error after upgrading :).

Have a nice evening,
Azerty
