### ISSUE TITLE
Error after update v3.0.1 'status_code_alias'

### ISSUE THREAD

**Issue by Maxxxel** [azerty9971/xtend_tuya#131]
Plugin won't load anymore after latest update. Here's the error from the log:

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 00:57:41 (2 Vorkommnisse)
Zuletzt protokolliert: 01:00:39

Error setting up entry gg-114981433539020916792 for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 46, in async_setup_entry
    await hass.async_add_executor_job(multi_manager.update_device_cache)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 148, in update_device_cache
    self._merge_devices_from_multiple_sources()
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 180, in _merge_devices_from_multiple_sources
    XTMergingManager.merge_devices(prev_device, current_device)
  File "/config/custom_components/xtend_tuya/multi_manager/shared/merging_manager.py", line 26, in merge_devices
    CloudFixes.apply_fixes(device1)
  File "/config/custom_components/xtend_tuya/multi_manager/shared/cloud_fix.py", line 28, in apply_fixes
    CloudFixes._fix_missing_aliases_using_status_format(device)
  File "/config/custom_components/xtend_tuya/multi_manager/shared/cloud_fix.py", line 418, in _fix_missing_aliases_using_status_format
    if status != status_code and status not in local_strategy["status_code_alias"]:
                                               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'status_code_alias'
```

**Comment by azerty9971** [comment]
Hello,
Can you retry with the latest release (3.0.2) ?

Sorry for the inconvenience,
Azerty

**Comment by Maxxxel** [comment]
> Hello,
> Can you retry with the latest release (3.0.2) ?
> 
> Sorry for the inconvenience,
> Azerty

Perfectly works again 👍🏼
