### ISSUE TITLE
Error after adding Tuya credentials and reloading integration

### ISSUE THREAD

**Issue by felipecrs** [azerty9971/xtend_tuya#141]
If I add the Tuya credentials, and then reload the integration, the following happens:

![image](https://github.com/user-attachments/assets/eeed3b2d-ccf9-41d6-85b9-387c15496e3e)

Note that during the credential's setup itself, no error is thrown.

I enabled debug diagnostics during the integration reload and attached the logs:
[error_log (2).txt](https://github.com/user-attachments/files/17551596/error_log.2.txt)

**Comment by EstrianTech** [comment]
I am also getting this error

**Comment by eduardokabello** [comment]
The same error here

**Comment by azerty9971** [comment]
Hello,
Can you try with the latest stable 3.0.3?

Thanks,
Azerty

**Comment by felipecrs** [comment]
The same issue happens with 3.0.3.

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 2:33:37 PM (1 occurrences)
Last logged: 2:33:37 PM

Error setting up entry someemail@email.com for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 46, in async_setup_entry
    await hass.async_add_executor_job(multi_manager.update_device_cache)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 148, in update_device_cache
    self._merge_devices_from_multiple_sources()
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 180, in _merge_devices_from_multiple_sources
    XTMergingManager.merge_devices(prev_device, current_device)
  File "/config/custom_components/xtend_tuya/multi_manager/shared/merging_manager.py", line 31, in merge_devices
    XTMergingManager._align_api_usage(device1, device2)
  File "/config/custom_components/xtend_tuya/multi_manager/shared/merging_manager.py", line 168, in _align_api_usage
    match prefer:
          ^^^^^^
UnboundLocalError: cannot access local variable 'prefer' where it is not associated with a value
```

**Comment by felipecrs** [comment]
Oh, it actually worked on my second attempt. It takes a long time, but I guess that's not a problem.

https://github.com/user-attachments/assets/6d459938-e1de-427c-afa5-25570001445a

I tried a third time, and it worked too.

**Comment by azerty9971** [comment]
I've posted a new version (3.0.4) that should fix that issue (the second one about the prefer).

Can you validate that you no longer have the problem?

Thanks in advance,
Azerty

**Comment by felipecrs** [comment]
This issue no longer happens, it seems. Thank you!
