### ISSUE TITLE
G30 Door Lock missing entities in HA

### ISSUE THREAD

**Issue by jackmanou** [azerty9971/xtend_tuya#142]
Hi,

I have downloaded the Xtend Tuya from HACS, but have failed to install the integration getting the below error:

" _Config flow could not be loaded: {"message":"Invalid handler specified"}_ "

Even though all 3 devices are added through Xtend Tuya (lock, keypad, and bridge) their entities are not present. I am using HA through a new device from LinknLink the iSG. My HA core version is 2024.3.3, if this is helpful. Any ideas, if we can sort this out please, or what am I doing wrong? 

Thanks a lot! 
Antonis

**Comment by azerty9971** [comment]
Hello,
Can you post your system logs ?
("Settings" -> "System" -> "Logs").

Thanks in advance,
Azerty

**Comment by jackmanou** [comment]
Hello,

Thanks for the reply. I belive this is what you want (I am a newbie of course, so hope this is correct). 
I found two errors, here is one:

Logger: homeassistant.loader
Source: loader.py:1025
First occurred: 13:57:27 (1 occurrences)
Last logged: 13:57:27

Unexpected exception importing platform custom_components.xtend_tuya.config_flow
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/xtend_tuya/__init__.py", line 16, in <module>
    from .multi_manager.multi_manager import (
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 31, in <module>
    from .shared.shared_classes import (
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/xtend_tuya/multi_manager/shared/shared_classes.py", line 49
    type XTConfigEntry = ConfigEntry[HomeAssistantXTData]
         ^^^^^^^^^^^^^
SyntaxError: invalid syntax

and the second error:

Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 13:57:27 (1 occurrences)
Last logged: 13:57:27

Error occurred loading flow for integration xtend_tuya: Exception importing custom_components.xtend_tuya.config_flow

**Comment by azerty9971** [comment]
Hello,
I just figured out what is happening, you are using the version 3.11 of Python.

Home Assistant requires the version 3.12, that's why you are seeing this error message...

What type of installation have you done?

Have a nice day,
Azerty

**Comment by jackmanou** [comment]
Crap..

I am using Home Assistant through a device from LinknLink called iSG which has a build-in Home Assistant through an APK file. (I need to check about the Python version and revert)
When I had this issue, I was running Home Assistant version 2024.03. Now, we have been updated to 2024.11, and we are supposed to be upgrading monthly like everyone else. After the upgrade, I managed to find the missing entities (lock/unlock and I think all the sensors), however, the only problem remaining is the the unlock function through HA is not working.

I can change the auto-lock timer or lock the door when I press the button on HA, however when I click on the unlock button nothing is happening.

**Comment by azerty9971** [comment]
no need to downgrade if it now works in 2024.11 ;)

For your lock issue, have you done the following steps:
https://github.com/azerty9971/xtend_tuya/blob/main/docs/configure_locks.md

Have a nice day,
Azerty

**Comment by jackmanou** [comment]
I did NOT know that !!

Thanks a lot! 

Subscribed and will test this afternoon, appreciate the help

Best,
Antonis

**Comment by jackmanou** [comment]
Hi,

Just as a follow-up on this..
I ditched the crappy Home Assistant version of the iSG mentioned above and I am now running the official Home Assistant version on my laptop, so I had to re-do most of my Tuya integration stuff. So I created another Tuya developer account - linked it to my app - found all of my devices on HA through the xTend integrations, followed every step in the github page and I am still not able to unlock the door using the "unlock" button. I have all the other entities (auto lock time, beep volume, manual lock, alarm vilume etc..).

I also subscribed to the smart lock open service as well.

Any ideas what else I could try to make this work? 

Thanks a lot!

Best,
Antonis

**Comment by azerty9971** [comment]
Not really, can we schedule a google meet about this?
Would this sunday be OK for you to do that? (anytime in the afternoon GMT+1 time)

Thanks in advance,
Azerty

**Comment by jackmanou** [comment]
For sure yeah!

Not sure how to message you in github for more details, but I am OK for 4-5 pm gmt time (I live in Greece so I am GMT +2)

**Comment by azerty9971** [comment]
Would you be available now?
Sorry for the late reply, if so, join me on:
https://meet.google.com/qqj-nxcp-dku

Have a nice day,
Azerty

**Comment by jackmanou** [comment]
Sorry man, I saw the email 3 hours later..
If you are up for it, I am always available 6pm GMT+1 time on a business day, or else the weekend whenever you can.

Thanks!

**Comment by azerty9971** [comment]
Hello,
Sorry for the late reply.

Do you still encounter this issue?

Have a nice day,
Azerty

**Comment by jackmanou** [comment]
Hello!

To be honest I kinda gave on this device and its functions. I simply use it through the app itself and voice prompts.

Hoping someone will integrate the official lockin app, as one key feature was missing from tuya app as well, the auto-lock feature.

Anyhow, thanks again for the trouble!

Best,
Antonis

**Comment by azerty9971** [comment]
Hello,
XT v4.1.5 introduced generic entities that should hopefully implement all the missing entities that you want. Can you go on the device page and check the "disabled entities"?
In theory you should have everything that is supportable in there.
If not feel free to reopen this issue and post a device diagnostic (see https://github.com/azerty9971/xtend_tuya/issues/286)

If some entities are still missing and you are using the regular Tuya integration can you try removing the regular Tuya integration (Settings -> Device and services -> Tuya -> remove all the hubs there) and then restart HA, XT should take over and readd all the entities that were handled by the regular Tuya integration)

Let me know if it worked.

(I'm doing a bit of cleanup in the issue's backlog, that is why I'm closing quite a few of them, but don't hesitate to reopen this one if it still applies ;))

Have a nice day,
Azerty
