### ISSUE TITLE
Cannot delete integration entry

### ISSUE THREAD

**Issue by felipecrs** [azerty9971/xtend_tuya#145]
This happens:

https://github.com/user-attachments/assets/f8b87a04-299b-413e-8b89-d63f19b3e27f

[error_log (3).txt](https://github.com/user-attachments/files/17591171/error_log.3.txt)

**Comment by azerty9971** [comment]
Which version of HA are you using?

**Comment by felipecrs** [comment]
2024.10.4

**Comment by felipecrs** [comment]
The same thing works just fine in my brother's Home Assistant.

This seems to be the relevant log entry btw:

```
Logger: homeassistant.config_entries
Source: config_entries.py:862
First occurred: 2:27:58 PM (3 occurrences)
Last logged: 3:01:37 PM

Error calling entry remove callback felipecassiors@gmail.com for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 862, in async_remove
    await component.async_remove_entry(hass, self)
  File "/config/custom_components/xtend_tuya/__init__.py", line 142, in async_remove_entry
    await hass.async_add_executor_job(entry.runtime_data.multi_manager.unload)
                                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'
```

**Comment by azerty9971** [comment]
Can you retry with the latest BETA version please?

**Comment by felipecrs** [comment]
I no longer see that error in the logs, but I still can't delete the integration entry. Maybe I can delete it from .storage. I'll give it a try.

**Comment by felipecrs** [comment]
Ok, I was able to delete it by _Disabling_ the official Tuya integration, and only then deleting Xtend Tuya entry.

But then If I restart Home Assistant, Xtend Tuya shows up again even though I did not add it.

**Comment by azerty9971** [comment]
Could be that it's automatically reimporting the official Tuya integration entry...
I'm currently working on missing entities, will do that after (if I have the energy, I'm so tired today :'()

**Comment by felipecrs** [comment]
Got it. And don't worry about it, there's no rush at all.

**Comment by jebeke65** [comment]
Also have the same issue. 
How can I delete the integration ?

**Comment by jebeke65** [comment]
@azerty9971 Can you give an update please ?

**Comment by azerty9971** [comment]
you need to disable the regular Tuya, then delete XT then reenable Tuya :)

**Comment by jebeke65** [comment]
tx !
