### ISSUE TITLE
Broken since latest update - Country code? 

### ISSUE THREAD

**Issue by daveyeger** [azerty9971/xtend_tuya#174]
Can configure only if delete and works until restart.

![image](https://github.com/user-attachments/assets/d00a5cf6-dff4-4197-9d26-535185d5c4ab)

I set country code to US but it appears to flip to Canada.

**Comment by azerty9971** [comment]
Hello,
Canada and US actually use the same datacenter so this should not be an issue...

What exactly is not working when you restart?

Have a nice day,
Azerty

**Comment by daveyeger** [comment]
Here is raw log. Thank you for all you do for us!



2024-12-12 18:08:18.226 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry dxxxxx@gmail.com for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 46, in async_setup_entry
    await hass.async_add_executor_job(multi_manager.update_device_cache)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 148, in update_device_cache
    self._merge_devices_from_multiple_sources()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 180, in _merge_devices_from_multiple_sources
    XTMergingManager.merge_devices(prev_device, current_device)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/shared/merging_manager.py", line 26, in merge_devices
    CloudFixes.apply_fixes(device1)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/shared/cloud_fix.py", line 27, in apply_fixes
    CloudFixes._fix_missing_range_values_using_local_strategy(device)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/shared/cloud_fix.py", line 442, in _fix_missing_range_values_using_local_strategy
    for new_range_value in status_range_range_dict:
                           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by daveyeger** [comment]
Also seeing this:

Logger: tuya_iot
Source: /usr/local/lib/python3.13/site-packages/tuya_iot/openmq.py:117
First occurred: 6:17:43 PM (21 occurrences)
Last logged: 6:18:24 PM

Unexpected disconnection.7

**Comment by daveyeger** [comment]
Still shows Canada on restart but works as expected. Thank you so much for the fast turnaround.

**Comment by azerty9971** [comment]
You're welcome :).

Happy holiday season!!
Azerty
