### ISSUE TITLE
Error unloading

### ISSUE THREAD

**Issue by thorin8k** [azerty9971/xtend_tuya#184]
I've recently started using this custom component and everything seems to work fine until night. It has happened two days, when I wake up the tuya integration  says that all devices are unavailable and this error is in the logs:

```Registrador: homeassistant.config_entries
Fuente: config_entries.py:855
Ocurrió por primera vez: 08:00:00 (1 ocurrencias)
Última vez registrado: 08:00:00

Error unloading entry xxxx@yyyy.com for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/multi_manager/tuya_sharing/ha_tuya_integration/tuya_decorators.py", line 30, in wrapped
    await callback(False, *args, **kwargs)
  File "/config/custom_components/xtend_tuya/multi_manager/tuya_sharing/ha_tuya_integration/config_entry_handler.py", line 43, in on_tuya_unload_entry
    self.manager.reuse_config = False
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'reuse_config' of 'XTSharingDeviceManager' object has no setter

```

Specs: 
- HA version: 2024.12.3
- HAOS version: 13.1
- xtend tuya: 3.0.7

**Comment by thorin8k** [comment]
I've found something else. I forgot I had an automation to reload the main tuya integration every day.

The problem happens when trying to reload the main tuya integration. 

Maybe once xtend tuya is installed, the main one cannot be reloaded?

When reloading the xtend tuya, it reloads the whole tuya devices?

**Comment by azerty9971** [comment]
Hello,
This has been fixed in my dev branch, I'll publish a release soon (testing some other stuff before doing the release).

Sorry for the inconvenience,
Azerty

**Comment by azerty9971** [comment]
Hello,
Can you retry with 3.0.8-beta.1?

It should fix the issue :).

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Hello,
This issue should be resolved in v4.0.0.

If it's not the case please reopen this issue.

Have a nice day,
Azerty
